zuul:
  routes:
    frontend:
      path: /frontend/**
      serviceId: frontend-service
    identity:
      path: /identity/**
      serviceId: identity-service
      sensitiveHeaders:
    catalog:
      path: /catalog/**
      serviceId: catalogue-service-srdc
      sensitiveHeaders: Cookie,Set-Cookie
    
spring:
  http:
    multipart:
     max-file-size: 1000MB
     max-request-size: 1000MB


---

spring:
  profiles: dev

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 8
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 2

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 500000

zuul:
  eureka:
    identity-service:
      semaphore:
        maxSemaphores: 300
  host:
    connect-timeout-millis: 1000000
    socket-timeout-millis: 1000000
ribbon:
  ReadTimeout: 1000000
  ConnectTimeout: 1000000
